FROM ubuntu:latest
MAINTAINER Chris Timperley "christimperley@gmail.com"

# install auto* tools
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y autoconf
RUN apt-get install -y build-essential gcc
