#!/bin/bash
#
# Used by the host to issue a pre-process request, which is then forwarded onto
# the appropriate Docker instance, via this script. The pre-processed files,
# together with all other compilation artefacts, are left in the repository
# directory. It is the responsibility of the host to fetch the particular
# pre-processed in which it is interested in, and not that of this script.
#
# USAGE:
# ./preprocess [repository-location] [dockerfile-location]
#
this_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
support_dir="$this_dir/../docker"

repository=$1
#dockerfile=$2
#dockerimage="bughunter:$1"
dockerimage=$2

# Ensure the image has been built from the dockerfile
#docker build -t $dockerimage "$2" || exit 1

# Mount the repository at /repository, and the pre-processing script at
# /bughunter/preprocess, then execute the preprocess executable
docker run --rm \
  -v "$repository":/repository \
  -v "$support_dir":/bughunter \
  $dockerimage \
  /bin/bash /bughunter/preprocessor.sh
